language: node_js
node_js:
- '0.10'
before_script:
- npm -g install bower
- bower install
script: npm run build
after_success:
- "./_travis/deploy-gh-pages.sh"
env:
  global:
  - GH_REPO="azu/power-assert-demo"
  - secure: aDtR7a39wdjwxlB3kEruzNSpzfUMk+aqpOVaS5yAXkv+TTdr1qKOyNQd7OlNr5nVROTG2OXyGXvcQvyCdNztpI4CV4mMxe/zauo6VMXPe2KxunGxkOPYFOkwAHvOw5a4gpqXIxJG+qFkZ9Ykmvb5Z1X2GLfH5Sd2BCFXUM9izl8=
